SELECT DISTINCT(h.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR r ON h.CAR_ID = r.CAR_ID
WHERE CAR_TYPE = '세단' AND ('2022-10-01' <= START_DATE AND START_DATE < '2022-11-01')
ORDER BY CAR_ID DESC;