SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
    JOIN PATIENT p ON a.PT_NO = p.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%' AND d.MCDP_CD = 'CS' AND APNT_CNCL_YMD IS NULL
ORDER BY APNT_YMD;